import { ReviewStatus, ApplicationType, AuthenticationType, DataType, ActionType, BackoffStrategy } from '../types.js';
import { CapabilityArtifact, CapabilityArtifactSchema } from '../schema.js';

/**
 * Mariner Pro Example Artifact
 * Capability: "Find Auxiliary Engine course and open the Construction section"
 *
 * This is a hand-crafted schema fixture for testing purposes, not generated by an LLM.
 */

export const marinerProExampleArtifact: CapabilityArtifact = {
  metadata: {
    name: 'Find Auxiliary Engine Course and Open Construction Section',
    description: 'Navigate to Mariner Pro, search for the Auxiliary Engine course, and open the Construction section',
    tags: ['mariner-pro', 'course-navigation', 'section-extraction'],
    category: 'course-management',
  },
  version: {
    version: 1,
    createdBy: 'system',
    createdAt: new Date('2024-01-15T10:00:00Z').toISOString(),
    reviewStatus: ReviewStatus.DRAFT,
    changelog: 'Initial version - basic course navigation and section extraction',
  },
  tenant: {
    tenantId: undefined,
    isGlobal: true,
  },
  target: {
    applicationType: ApplicationType.WEB,
    url: 'https://mariner-pro.example.com',
    platform: 'mariner-pro',
    authentication: {
      type: AuthenticationType.SESSION,
      requirements: ['Valid session cookie required'],
    },
  },
  inputs: [
    {
      name: 'courseName',
      type: DataType.STRING,
      required: true,
      validation: {
        type: DataType.STRING,
        constraints: {
          minLength: 1,
          maxLength: 100,
          pattern: '^[a-zA-Z0-9\\s-]+$',
        },
      },
      defaultValue: 'Auxiliary Engine',
    },
    {
      name: 'sectionName',
      type: DataType.STRING,
      required: true,
      validation: {
        type: DataType.STRING,
        constraints: {
          minLength: 1,
          maxLength: 100,
          pattern: '^[a-zA-Z0-9\\s-]+$',
        },
      },
      defaultValue: 'Construction',
    },
  ],
  outputs: [
    {
      name: 'courseUrl',
      type: DataType.STRING,
      extractionRule: 'window.location.href',
      successCondition: 'url matches "^https://mariner-pro.example.com/courses/.*"',
    },
    {
      name: 'sectionContent',
      type: DataType.STRING,
      extractionRule: 'document.querySelector(".section-content")?.textContent',
      successCondition: 'element.count > 0',
    },
  ],
  steps: [
    {
      stepId: 'navigate-to-courses',
      order: 1,
      description: 'Navigate to the courses page',
      action: {
        type: ActionType.NAVIGATE,
        value: 'https://mariner-pro.example.com/courses',
        timeout: 10000,
      },
      checkpoint: {
        condition: 'url matches "^https://mariner-pro.example.com/courses"',
        successCriteria: 'Page loaded successfully',
        failureHandling: 'fail',
      },
      retryPolicy: {
        maxAttempts: 3,
        backoffStrategy: BackoffStrategy.FIXED,
        backoffMs: 1000,
        retryableErrors: ['network_error', 'timeout'],
      },
    },
    {
      stepId: 'search-course',
      order: 2,
      description: 'Search for the course by name',
      action: {
        type: ActionType.TYPE,
        selectors: [
          {
            type: 'css',
            value: '#search-input',
          },
        ],
        value: '{{courseName}}',
        timeout: 5000,
      },
      checkpoint: {
        condition: 'element.visible == true',
        successCriteria: 'Search input is visible and focused',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'click-search',
      order: 3,
      description: 'Click the search button',
      action: {
        type: ActionType.CLICK,
        selectors: [
          {
            type: 'css',
            value: '#search-button',
          },
        ],
        timeout: 5000,
      },
      checkpoint: {
        condition: 'element.visible == true',
        successCriteria: 'Search button clicked',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'wait-for-results',
      order: 4,
      description: 'Wait for search results to load',
      action: {
        type: ActionType.WAIT,
        timeout: 10000,
        waitCondition: 'element.visible == true',
      },
      checkpoint: {
        condition: 'element.count > 0',
        successCriteria: 'Search results are displayed',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'click-course-result',
      order: 5,
      description: 'Click on the course result',
      action: {
        type: ActionType.CLICK,
        selectors: [
          {
            type: 'css',
            value: '.course-result:first-child',
          },
        ],
        timeout: 5000,
      },
      checkpoint: {
        condition: 'url contains "course"',
        successCriteria: 'Navigated to course page',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'wait-for-course-page',
      order: 6,
      description: 'Wait for course page to load',
      action: {
        type: ActionType.WAIT,
        timeout: 10000,
        waitCondition: 'element.visible == true',
      },
      checkpoint: {
        condition: 'element.visible == true',
        successCriteria: 'Course page loaded',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'navigate-to-sections',
      order: 7,
      description: 'Navigate to sections tab',
      action: {
        type: ActionType.CLICK,
        selectors: [
          {
            type: 'css',
            value: '#sections-tab',
          },
        ],
        timeout: 5000,
      },
      checkpoint: {
        condition: 'element.visible == true',
        successCriteria: 'Sections tab is active',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'find-section',
      order: 8,
      description: 'Find and click the Construction section',
      action: {
        type: ActionType.CLICK,
        selectors: [
          {
            type: 'text',
            value: 'Construction',
          },
        ],
        timeout: 5000,
      },
      checkpoint: {
        condition: 'element.text contains "Construction"',
        successCriteria: 'Construction section is selected',
        failureHandling: 'retry',
      },
    },
    {
      stepId: 'extract-content',
      order: 9,
      description: 'Extract section content',
      action: {
        type: ActionType.EXTRACT,
        selectors: [
          {
            type: 'css',
            value: '.section-content',
          },
        ],
        timeout: 5000,
      },
      checkpoint: {
        condition: 'element.count > 0',
        successCriteria: 'Section content extracted',
        failureHandling: 'fail',
      },
    },
    {
      stepId: 'validate-content',
      order: 10,
      description: 'Validate that section content is not empty',
      action: {
        type: ActionType.WAIT,
        timeout: 2000,
      },
      checkpoint: {
        condition: 'element.count > 0',
        successCriteria: 'Section content is loaded and not empty',
        failureHandling: 'fail',
      },
    },
  ],
  safety: {
    allowedDomains: ['https://mariner-pro.example.com'],
    restrictedActions: [ActionType.TYPE], // Restrict typing to avoid unintended form submissions
    dataExtractionRules: ['Only extract public course content', 'Do not extract user data'],
    humanApprovalRequired: false,
  },
};

/**
 * Validate the example artifact against the schema
 */
export function validateMarinerProExample(): CapabilityArtifact {
  return CapabilityArtifactSchema.parse(marinerProExampleArtifact);
}
