import { CapabilityArtifact, CapabilityArtifactSchema } from '../../capability/schema.js';
import { ReviewStatus, ApplicationType, AuthenticationType, DataType, ActionType, BackoffStrategy } from '../../capability/types.js';
import { ExecutionTrace, TraceStep } from '../trace/types.js';
import { mapTargetToSelector } from '../actions/schema.js';

/**
 * Generate Capability Artifact from execution trace
 */
export function generateArtifact(trace: ExecutionTrace): CapabilityArtifact {
  const metadata = inferMetadata(trace);
  const version = inferVersionMetadata();
  const tenant = inferTenantInfo();
  const target = inferTargetDescriptor(trace);
  const inputs = inferInputs(trace);
  const outputs = inferOutputs(trace);
  const steps = mapActionsToSteps(trace.steps);
  const safety = inferSafetyPolicy(trace.targetUrl);

  const artifact = {
    metadata,
    version,
    tenant,
    target,
    inputs,
    outputs,
    steps,
    safety,
  };

  // Validate against Phase 2 schema
  return CapabilityArtifactSchema.parse(artifact);
}

/**
 * Infer metadata from trace
 */
function inferMetadata(trace: ExecutionTrace) {
  return {
    name: generateCapabilityName(trace.goal),
    description: trace.goal,
    tags: inferTags(trace),
    category: inferCategory(trace),
  };
}

/**
 * Generate capability name from goal
 */
function generateCapabilityName(goal: string): string {
  // Simple name generation from goal
  return goal
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .substring(0, 200);
}

/**
 * Infer tags from trace
 */
function inferTags(trace: ExecutionTrace): string[] {
  const tags: string[] = [];
  
  // Add platform tag from URL
  if (trace.targetUrl.includes('mariner')) {
    tags.push('mariner-pro');
  }
  
  // Add action-based tags
  const actionTypes = new Set(trace.steps.map((step) => step.action.type));
  if (actionTypes.has(ActionType.NAVIGATE)) {
    tags.push('navigation');
  }
  if (actionTypes.has(ActionType.EXTRACT)) {
    tags.push('data-extraction');
  }
  
  return tags;
}

/**
 * Infer category from trace
 */
function inferCategory(trace: ExecutionTrace): string {
  if (trace.goal.toLowerCase().includes('course')) {
    return 'course-management';
  }
  if (trace.goal.toLowerCase().includes('search')) {
    return 'search';
  }
  if (trace.goal.toLowerCase().includes('form')) {
    return 'form-submission';
  }
  return 'general';
}

/**
 * Infer version metadata
 */
function inferVersionMetadata() {
  return {
    version: 1,
    createdBy: 'discovery-system',
    createdAt: new Date().toISOString(),
    reviewStatus: ReviewStatus.DRAFT,
    changelog: 'Initial version generated by LLM discovery',
  };
}

/**
 * Infer tenant info
 */
function inferTenantInfo() {
  return {
    tenantId: undefined,
    isGlobal: true,
  };
}

/**
 * Infer target descriptor
 */
function inferTargetDescriptor(trace: ExecutionTrace) {
  return {
    applicationType: ApplicationType.WEB,
    url: trace.targetUrl,
    platform: inferPlatform(trace.targetUrl),
    authentication: {
      type: AuthenticationType.SESSION,
      requirements: ['Valid session required'],
    },
  };
}

/**
 * Infer platform from URL
 */
function inferPlatform(url: string): string {
  if (url.includes('mariner')) {
    return 'mariner-pro';
  }
  return 'web';
}

/**
 * Infer inputs from trace
 */
function inferInputs(trace: ExecutionTrace) {
  const inputs: Array<{
    name: string;
    type: DataType;
    required: boolean;
    validation: {
      type: DataType;
      constraints: {
        minLength: number;
        maxLength: number;
      };
    };
    defaultValue: string;
  }> = [];
  
  // Extract values from type actions
  const typeActions = trace.steps.filter((step) => step.action.type === ActionType.TYPE);
  typeActions.forEach((action) => {
    if (action.action.value) {
      inputs.push({
        name: inferInputName(action.action.value),
        type: DataType.STRING,
        required: true,
        validation: {
          type: DataType.STRING,
          constraints: {
            minLength: 1,
            maxLength: 100,
          },
        },
        defaultValue: action.action.value,
      });
    }
  });
  
  return inputs;
}

/**
 * Infer input name from value
 */
function inferInputName(value: string): string {
  // Simple heuristic: convert value to camelCase name
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/**
 * Infer outputs from trace
 */
function inferOutputs(trace: ExecutionTrace) {
  const outputs: Array<{
    name: string;
    type: DataType;
    extractionRule: string;
    successCondition: string;
  }> = [];
  
  // Extract data from extract actions
  const extractActions = trace.steps.filter((step) => step.action.type === ActionType.EXTRACT);
  extractActions.forEach((action, index) => {
    outputs.push({
      name: `extractedData${index + 1}`,
      type: DataType.STRING,
      extractionRule: mapTargetToSelector(action.action.target)?.[0]?.value || 'element.textContent',
      successCondition: 'element.count > 0',
    });
  });
  
  // Add URL as output if navigation occurred
  if (trace.steps.some((step) => step.action.type === ActionType.NAVIGATE)) {
    outputs.push({
      name: 'finalUrl',
      type: DataType.STRING,
      extractionRule: 'window.location.href',
      successCondition: 'url matches ".*"',
    });
  }
  
  return outputs;
}

/**
 * Map executed actions to Phase 2 steps
 */
function mapActionsToSteps(traceSteps: TraceStep[]) {
  return traceSteps.map((step, index) => ({
    stepId: `step-${index + 1}`,
    order: index + 1,
    description: step.action.reasoning || `Execute ${step.action.type}`,
    action: {
      type: step.action.type,
      selectors: mapTargetToSelector(step.action.target),
      value: step.action.value,
      timeout: step.action.timeout,
    },
    checkpoint: step.result.success
      ? {
          condition: generateSimpleCheckpoint(step),
          successCriteria: step.result.description,
          failureHandling: 'fail' as const,
        }
      : undefined,
    retryPolicy: {
      maxAttempts: 3,
      backoffStrategy: BackoffStrategy.FIXED,
      backoffMs: 1000,
    },
  }));
}

/**
 * Generate simple checkpoint condition
 */
function generateSimpleCheckpoint(step: TraceStep): string {
  switch (step.action.type) {
    case ActionType.NAVIGATE:
      return 'url matches ".*"';
    case ActionType.CLICK:
    case ActionType.TYPE:
    case ActionType.SELECT:
      return 'element.visible == true';
    case ActionType.EXTRACT:
      return 'element.count > 0';
    case ActionType.WAIT:
      return 'page.loaded == true';
    default:
      return 'action.success == true';
  }
}

/**
 * Infer safety policy
 */
function inferSafetyPolicy(targetUrl: string) {
  const domain = new URL(targetUrl).hostname;
  
  return {
    allowedDomains: [`https://${domain}`],
    restrictedActions: [ActionType.TYPE], // Restrict typing to avoid unintended form submissions
    dataExtractionRules: ['Only extract public data', 'Do not extract user credentials'],
    humanApprovalRequired: false,
  };
}
